server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    # Use Kubernetes cluster DNS for service resolution
    resolver kube-dns.kube-system.svc.cluster.local valid=10s;

    location /users {
        set $upstream_user http://user-service:9001;
        proxy_pass $upstream_user;
    }
    location /products {
        set $upstream_product http://product-service:9000;
        proxy_pass $upstream_product;
    }
    location /cart {
        set $upstream_cart http://cart-service:9003;
        proxy_pass $upstream_cart;
    }
    location / {
        try_files $uri /index.html;
    }
}
