apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: eshtry-mny
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGO_USERNAME
      remoteRef:
        key: eshtry-mny/app-secrets
        property: MONGO_USERNAME
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: eshtry-mny/app-secrets
        property: MONGO_PASSWORD
    - secretKey: ACCESS_TOKEN
      remoteRef:
        key: eshtry-mny/app-secrets
        property: ACCESS_TOKEN
