apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: product-service-allow
  namespace: eshtry-mny
spec:
  podSelector:
    matchLabels:
      app: product-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app: cart-service
      ports:
        - protocol: TCP
          port: 9000
  egress:
    # DNS resolution (UDP + TCP port 53 to kube-system)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # MongoDB Atlas (external SaaS — allow to any IP on 27017)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 27017
